name: Daily Test Run

on:
  schedule:
    - cron: '10 9 * * *' # 2:40 PM IST
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        env: # 👈 pass secrets into environment
          BASE_URL: ${{ secrets.BASE_URL }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        run: npx playwright test

      - name: Generate Allure report
        if: always()
        run: npx allure generate allure-results --clean -o public/reports

      - name: Zip Allure report
        if: always()
        run: zip -r report.zip public/reports

      - name: Send email with report
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "Daily Playwright Test Report"
          to: ${{ secrets.EMAIL_USER }}
          from: "GitHub Actions <${{ secrets.EMAIL_USER }}>"
          body: |
            Hi Pratik,

            Please find attached the latest Playwright Allure test report.

            Best,
            GitHub Actions
          attachments: report.zip