name: Daily Test Run

on:
  schedule:
    - cron: '0 8 * * *' # 1:30 PM IST
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - name: Generate Allure report
        run: |
          npx allure generate allure-results --clean -o public/reports

      - name: Send email with report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "Daily Playwright Test Report"
          to: pratikv8070@gmail.com
          from: GitHub Actions <${{ secrets.EMAIL_USER }}>
          body: "Hi Pratik,\n\nHere is the latest Playwright Allure test report.\n\nBest,\nGitHub Actions"
          attachments: public/reports/index.html